# Generated by Django 4.0.2 on 2022-02-05 15:07

from django.db import migrations, models
import petstagram.main_app.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_profile_email_alter_profile_first_name_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', validators=[petstagram.main_app.custom_validators.validate_file_max_size])),
                ('description', models.TextField(blank=True, null=True)),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0)),
                ('tagged_pets', models.ManyToManyField(to='main_app.Pet')),
            ],
        ),
    ]
